language: bash
sudo: false
services: docker
addons:
  apt_packages:
    - context
    - pandoc
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-latex-recommended
before_install:
  - "wget -q -O - https://github.com/yihui/crandalf/raw/master/inst/scripts/install-pandoc | bash"
install:
  - make
notifications:
  email: brucellino@gmail.com
