language: bash
sudo: required
services: docker
before_install:
  - sudo apt-get install build-essential
  - sudo apt-get install pandoc context
install:
  - make
notifications:
  email: brucellino@gmail.com
